project:
  name: quickstart-snyk-security
  owner: partners@snyk.io
  lambda_source_path: functions/source
  lambda_zip_path: functions/packages
  s3_regional_buckets: true
tests:
  full-no-auto:
    parameters:
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      SnykExternalId: abcd1234-abcd-1234-abcd-1234abcd1234
      SnykAWSAccountNumber: 198361731867
    regions:
      - us-east-1
    template: templates/snyk-full.template.yaml
