// We need to work around Step numbers here if we are going to potentially exclude the AMI subscription
=== Sign in to your AWS account

. Sign in to your AWS account at https://aws.amazon.com[https://aws.amazon.com^] with an IAM user role that has the necessary permissions. For more information, see link:#_planning_the_deployment[Planning the deployment], earlier in this guide.
. Ensure that your AWS account is configured correctly, as discussed in the link:#_technical_requirements[Technical requirements] section.

// Optional based on Marketplace listing. Not to be edited
ifdef::marketplace_subscription[]
=== Sign in to your {partner-product-short-name} account

This Quick Start requires a registered {partner-product-short-name} account through any plan: free, standard, pro, or enterprise.
To purchase Standard or Pro plans through the AWS Marketplace, follow these steps:

. Sign in to your AWS account.
. Navigate to the {marketplace_listing_url}[{partner-product-short-name}: Developer Security Platform^] page in AWS Marketplace, and choose *Continue to Subscribe*.
. Review the terms and conditions for software usage, and choose *Accept Terms*. +
A confirmation page loads, and an email confirmation is sent to the account owner. For more information, see the https://aws.amazon.com/marketplace/help/200799470[Getting started as a buyer^].

. When the subscription process completes, exit AWS Marketplace without further action.
endif::marketplace_subscription[]
// \Not to be edited

=== Launch the Quick Start
// Adapt the following warning to your Quick Start.

NOTE: You are responsible for the cost of the AWS services and any third-party licenses used while running this Quick Start. There is no additional cost for using the Quick Start.

Each deployment takes about {deployment_time} to complete.

. Sign in to your AWS account, and choose one of the following options to launch the AWS CloudFormation template. For help with choosing an option, see link:#_deployment_options[Deployment options], earlier in this guide.

[cols=2*]
|===
^|https://fwd.aws/E4m9w?[Deploy {partner-product-short-name} Security full integration on AWS^]
^|https://fwd.aws/6Jean?[View template^]

^|https://fwd.aws/Nx5kQ?[Deploy {partner-product-short-name} Security with Amazon ECR^]
^|https://fwd.aws/aPjng?[View template^]

^|https://fwd.aws/Nx5kQ?[Deploy {partner-product-short-name} Security with Amazon ECR and automated Snyk integration^]
^|https://fwd.aws/aPjng?[View template^]

^|https://fwd.aws/8rKEy?[Deploy {partner-product-short-name} Security with AWS Lambda^]
^|https://fwd.aws/JXd7k?[View template^]
|===

[start=2]
. Check the AWS Region that’s displayed in the upper-right corner of the navigation bar, and change it if necessary. This Region is where the network infrastructure for {partner-product-short-name} is built. The template launches in the {default_deployment_region} Region by default.

// *Note:* This deployment includes Amazon EFS, which isn’t currently supported in all AWS Regions. For a current list of supported Regions, see the https://docs.aws.amazon.com/general/latest/gr/elasticfilesystem.html[endpoints and quotas webpage].

[start=3]
. On the *Create stack* page, keep the default setting for the template URL, and then choose *Next*.
. On the *Specify stack details* page, change the stack name if needed. Review the parameters for the template, and provide values for any parameters that require input. For all other parameters, review the default settings, and customize them as necessary. When you finish reviewing and customizing the parameters, choose *Next*.
