// Replace the content in <>
// Briefly describe the software. Use consistent and clear branding. 
// Include the benefits of using the software on AWS, and provide details on usage scenarios.

=== About Snyk
Snyk provides the following products that can help secure your applications:

* Snyk Open Source: Finds and fixes open-source vulnerabilities.
* Snyk Container: Finds and fixes vulnerabilities in container images and Kubernetes applications.
* Snyk Infrastructure as Code (IaC): Finds and fixes insecure configurations in IaC tools and Kubernetes code.
* Snyk Intel Vulnerability Database Access: Provides comprehensive and actionable open-source and container vulnerability data.
* Snyk License Compliance Management: Identifies, monitors, and manages open-source license usage across your projects.

==== Snyk container and Amazon ECR

Snyk integrates with Amazon ECR to help you import projects and monitor containers for vulnerabilities. Snyk tests your imported projects for known security vulnerabilities at a frequency that you define. Integration with Amazon ECR is available for all pricing plans. For more information, see https://snyk.io/product/container-vulnerability-management/[Snyk Container^].

==== Snyk open source and AWS Lambda

Snyk integrates with AWS Lambda to help you monitor your AWS Lambda resources. With this integration, you can scan Lambda functions deployed to your AWS account and manage your code's security by identifying vulnerabilities and receiving remediation advice.
