// Replace the content in <>
// Briefly describe the software. Use consistent and clear branding. 
// Include the benefits of using the software on AWS, and provide details on usage scenarios.

=== About Snyk
Snyk empowers software-driven businesses to develop fast and stay secure. Snyk offers several products to secure your
applications:

* Snyk Open Source - Enabling developers to easily find and automatically fix open source vulnerabilities.
* Snyk Container - Find and fix vulnerabilities in container images and Kubernetes applications.
* Snyk Infrastructure as Code - Find and fix insecure configurations in IaC tools and Kubernetes code.
* Snyk Intel Vulnerability DB Access - Comprehensive and actionable open source and container vulnerability data.
* Snyk License Compliance Management - Identify, monitor and manage open source license usage across your projects.

==== Snyk Container & Amazon Elastic Container Registry (ECR)

Snyk integrates with Amazon Elastic Container Registry (ECR) to enable you to import your projects and monitor your
containers for vulnerabilities, as is fully described in our Container vulnerability management documentation. Snyk
tests the projects you’ve imported for any known security vulnerabilities found, at a frequency you control. Integration
with Amazon ECR is available for all of our pricing plans.

==== Snyk Open Source & AWS Lambda

Snyk integrates with AWS Lambda to enable you to monitor your deployed AWS Lambda resources. With this integration you
can scan Lambda functions deployed to your AWS account and start managing the security of your code by identifying
vulnerabilities and getting fix advice.
