//Include any postdeployment steps here, such as steps necessary to test that the deployment was successful. If there are no postdeployment steps leave this file empty.

== Postdeployment steps

=== Snyk integration with Amazon ECR
Deploying the Snyk security Partner Solution for Amazon Elastic Container Registry (Amazon ECR) creates
an integration for your Snyk organization. After it deploys, you can
add repositories for Snyk to scan by following these steps:

. Log in to your Snyk account.
. Navigate to *Projects*, choose *Add projects*, and then choose *Amazon ECR*.
. Select either single or multiple images.
. Choose *Add selected repositories*.

For more information, refer to https://support.snyk.io/hc/en-us/articles/360003947077-Amazon-Elastic-Container-Registry-ECR-add-images-to-Snyk[Amazon ECR: add images to Snyk^].

NOTE: Both integration options connect the deployed Amazon ECR instance to the Snyk organization provided in the Partner Solution parameters. Deployment may fail, however, if your chosen Snyk organization has an existing ECR integration or if the authentication token you provide in the parameters has insufficient permissions.

=== Snyk integration with AWS Lambda
. Log in to your Snyk account.
. Navigate to *Projects*, choose *Add projects*, and then choose *AWS Lambda*.
. Select the relevant functions.
. Choose *Add selected functions*.

NOTE: Snyk supports integrating with AWS Lambda for Node.js, Ruby, and Java projects.

For more information, refer to https://support.snyk.io/hc/en-us/articles/360004002418-AWS-Lambda-integration[AWS Lambda integration^].