---
AWSTemplateFormatVersion: '2010-09-09'
Description: Snyk integration for Amazon Elastic Container Registry (ECR). (qs-1sd1mkoa1)
Outputs:
  AWSRegion:
    Description: The AWS Region for your Snyk ECR intgration
    Value: !Sub '${AWS::Region}'
  SnykECRIntegrationRole:
    Description: Snyk ECR Integration Role ARN
    Value: !GetAtt 'SnykECRIntegrationRole.Arn'
  Version:
    Description: Snyk ECR Integration Version
    Value: 1.0.3
  NewSnykOrg:
    Description: Newly created Organization in your Snyk account
    Value: !GetAtt CreateSnykIntegration.newOrgId
Metadata:
  QSLint:
    Exclusions: [W9006]
  QuickStartDocumentation:
    EntrypointName: "Snyk integration for Amazon ECR"
    Order: "3"
  LICENSE: Apache License, Version 2.0
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Snyk
        Parameters:
          - SnykGroupId
          - SnykAuthToken
          - SnykAWSAccountNumber
          - ECRResourceARN
    ParameterLabels:
      SnykGroupId:
        default: Snyk Group ID to associate with new Org
      SnykAuthToken:
        default: Snyk API authentication token with Snyk Group admin permission, preferably a service account token
      SnykOrgPatternPrefix:
        default: Snyk Organization name prefix
      SnykAWSAccountNumber:
        default: Snyk AWS Account ID
      ECRResourceARN:
        default: ECR Resource ARN
Parameters:
  SnykGroupId:
    Description: "Locate the Group ID by logging in to https://app.snyk.io and navigating to Settings in the Group overview dashboard."
    Type: String
    AllowedPattern: '[a-z0-9-]{36}'
    MinLength: 1
  SnykAuthToken:
    Description: >
      Locate your account's API token by logging in to https://app.snyk.io and navigating to Account Settings.
      It is recommended that you use a Service Account token instead of your personal API Token. Whichever you choose,
      the token must have Group administrator permission. Refer to the integration guide for details.
    Type: String
    AllowedPattern: '[a-z0-9-]{36}'
    MinLength: 1
    NoEcho: True
  SnykOrgPatternPrefix:
    Description: "Provide a string to use as a prefix for the new organization that will be created within your Snyk group."
    Type: String
    AllowedPattern: ^[0-9a-zA-z]*
    MinLength: 1
  SnykAWSAccountNumber:
    Description: "Snyk's AWS Account ID which assumes a role in your account. Please see the deployment guide 'Technical requirements | Snyk Account Access' for this Account ID"
    Type: String
  QSS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription:
      Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen
      (-).
    Default: aws-quickstart
    Description:
      S3 bucket name for the Quick Start assets. This string can include
      numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start
      or end with a hyphen (-).
    Type: String
  QSS3BucketRegion:
    Default: 'us-east-1'
    Description: The AWS Region where the Quick Start S3 bucket (QSS3BucketName) is hosted. When using your own bucket, you must specify this value.
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: ^[0-9a-zA-Z-/.]*$
    ConstraintDescription:
      Quick Start key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), dots(.) and forward slash (/).
    Default: quickstart-snyk-security/
    Description:
      S3 key prefix for the Quick Start assets. Quick Start key prefix
      can include numbers, lowercase letters, uppercase letters, hyphens (-), dots(.) and
      forward slash (/).
    Type: String
  ECRResourceARN:
    Description: The ARN of the ECR resource(s). List multiple resource ARN's separated by a comma.
    Type: CommaDelimitedList
    Default: '*'
Conditions:
  UsingDefaultBucket: !Equals
    - !Ref QSS3BucketName
    - 'aws-quickstart'
Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
            Action:
            - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  AddSnykIntegrationLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
        S3Key: !Sub '${QSS3KeyPrefix}functions/packages/AddSnykIntegration/lambda.zip'
      Environment:
        Variables:
          awsRegion: !Ref QSS3BucketRegion
          awsRoleArn: !GetAtt SnykECRIntegrationRole.Arn
          groupId: !Ref SnykGroupId
          orgPatternPrefix: !Ref SnykOrgPatternPrefix
          authToken: !Ref SnykAuthToken
      Handler: lambda_function.handler
      Runtime: nodejs14.x
      Timeout: 30
      Role: !GetAtt LambdaExecutionRole.Arn
  CreateSnykIntegration:
    Type: Custom::CreateSnykIntegration
    Properties:
      ServiceToken: !GetAtt AddSnykIntegrationLambdaFunction.Arn
      Region: !Ref 'AWS::Region'
      SnykAuthToken: !Ref 'SnykAuthToken'
      SnykGroupId: !Ref 'SnykGroupId'
      SnykOrgPatternPrefix: !Ref 'SnykOrgPatternPrefix'
  SnykECRIntegrationRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:${AWS::Partition}:iam::${SnykAWSAccountNumber}:root
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                'sts:ExternalId': !Ref 'SnykGroupId'
      Path: /snyk/
      Policies:
        - PolicyName: AmazonEC2ContainerRegistryReadOnlyForSnyk
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'ecr:GetAuthorizationToken'
                Resource: '*'
              - Effect: Allow
                Action:
                  [
                    'ecr:GetLifecyclePolicyPreview',
                    'ecr:GetDownloadUrlForLayer',
                    'ecr:BatchGetImage',
                    'ecr:DescribeImages',
                    'ecr:GetAuthorizationToken',
                    'ecr:DescribeRepositories',
                    'ecr:ListTagsForResource',
                    'ecr:ListImages',
                    'ecr:BatchCheckLayerAvailability',
                    'ecr:GetRepositoryPolicy',
                    'ecr:GetLifecyclePolicy'
                  ]
                Resource: !Ref ECRResourceARN
