---
AWSTemplateFormatVersion: '2010-09-09'
Description: Snyk integration on AWS. (qs-1qm9kh0j6)
Outputs:
  AWSRegion:
    Description: AWS Region for your Snyk integration.
    Value: !Sub '${AWS::Region}'
  SnykECRIntegrationRole:
    Description: Amazon Resource Name (ARN) role for Snyk integration.
    Value: !GetAtt 'ECRIntegrationStack.Outputs.SnykECRIntegrationRole'
  SnykLambdaIntegrationRole:
    Description: ARN of the IAM role used to integrate Snyk with AWS Lambda resources.
    Value: !GetAtt 'LambdaIntegrationStack.Outputs.SnykLambdaIntegrationRole'
  Version:
    Description: Snyk integration version.
    Value: 1.0.2
Metadata:
  cfn-lint: { config: { ignore_checks: [ W9901 ] } }
  QSLint:
    Exclusions: [W9006]
  QuickStartDocumentation:
    EntrypointName: "Snyk integration for AWS"
    Order: "1"
  LICENSE: Apache License, Version 2.0
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Snyk
        Parameters:
          - SnykExternalId
          - SnykAWSAccountNumber
      - Label:
          default: AWS Quick Start configuration
        Parameters:
          - QSS3BucketName
          - QSS3BucketRegion
          - QSS3KeyPrefix
    ParameterLabels:
      SnykExternalId:
        default: Snyk organization ID(s)
      SnykAWSAccountNumber:
        default: Snyk AWS account ID
      QSS3BucketName:
        default: Quick Start S3 bucket name
      QSS3BucketRegion:
        default: Quick Start S3 bucket Region
      QSS3KeyPrefix:
        default: Quick Start S3 key prefix
Parameters:
  SnykExternalId:
    Description: "Enter your Snyk group ID. To locate your group ID, log in to https://app.snyk.io, and navigate to account settings. For multiple organizations, separate each ID with a comma."
    Type: CommaDelimitedList
  SnykAWSAccountNumber:
    Description: "Snyk's AWS account ID that assumes a role in your account."
    Type: String
  QSS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription:
     The S3 bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-), but it cannot start or end with a hyphen.
    Default: aws-quickstart
    Description:
      'Name of the S3 bucket for your copy of the deployment assets. Keep the default name unless you are customizing the template. Changing the name updates code references to point to a new location.'
    Type: String
  QSS3BucketRegion:
    Default: 'us-east-1'
    Description: 'AWS Region where the S3 bucket (QSS3BucketName) is hosted. Keep the default Region unless you are customizing the template. Changing the Region updates code references to point to a new location. When using your own bucket, specify the Region.'
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: ^[0-9a-zA-Z-/.]*$
    ConstraintDescription:
      The S3 key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slashes (/). End the prefix with a forward slash.
    Default: quickstart-snyk-security/
    Description:
      'S3 key prefix that is used to simulate a folder for your copy of the deployment assets. Keep the default prefix unless you are customizing the template. Changing this prefix updates code references to point to a new location.'
    Type: String
Conditions:
  UsingDefaultBucket: !Equals
    - !Ref QSS3BucketName
    - 'aws-quickstart'
Resources:
  ECRIntegrationStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        SnykExternalId: !Join [",", !Ref 'SnykExternalId']
        SnykAWSAccountNumber: !Ref 'SnykAWSAccountNumber'
      TemplateURL: !Sub
        - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/snyk-ecr.template.yaml'
        - S3Bucket: !If
            - UsingDefaultBucket
            - !Sub 'aws-quickstart-${AWS::Region}'
            - !Ref 'QSS3BucketName'
          S3Region: !If
            - UsingDefaultBucket
            - !Ref 'AWS::Region'
            - !Ref 'QSS3BucketRegion'
  LambdaIntegrationStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        SnykExternalId: !Join [",", !Ref 'SnykExternalId']
        SnykAWSAccountNumber: !Ref 'SnykAWSAccountNumber'
      TemplateURL: !Sub
        - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/snyk-lambda.template.yaml'
        - S3Bucket: !If
            - UsingDefaultBucket
            - !Sub 'aws-quickstart-${AWS::Region}'
            - !Ref 'QSS3BucketName'
          S3Region: !If
            - UsingDefaultBucket
            - !Ref 'AWS::Region'
            - !Ref 'QSS3BucketRegion'
