---
AWSTemplateFormatVersion: '2010-09-09'
Description: Snyk integration for Amazon Elastic Container Registry (ECR). (qs-1qqfgjgee)
Outputs:
  AWSRegion:
    Description: The AWS Region for your Snyk ECR intgration
    Value: !Sub '${AWS::Region}'
  SnykECRIntegrationRole:
    Description: Snyk ECR Integration Role ARN
    Value: !GetAtt 'SnykECRIntegrationRole.Arn'
  Version:
    Description: Snyk ECR Integration Version
    Value: 1.0.2
Metadata:
  QSLint:
    Exclusions: [W9006]
  QuickStartDocumentation:
    EntrypointName: "Snyk integration for Amazon ECR"
    Order: "3"
  LICENSE: Apache License, Version 2.0
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Snyk
        Parameters:
          - SnykExternalId
    ParameterLabels:
      SnykExternalId:
        default: Snyk organization ID
Parameters:
  SnykExternalId:
    Description: Locate the organization ID by logging in to https://app.snyk.io and navigating to Settings.
    Type: String
    AllowedPattern: '[a-z0-9-]{36}'
    MinLength: 1
Resources:
  SnykECRIntegrationRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::198361731867:root
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                'sts:ExternalId': !Ref 'SnykExternalId'
      Path: /snyk/
      Policies:
        - PolicyName: AmazonEC2ContainerRegistryReadOnlyForSnyk
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  [
                    'ecr:GetLifecyclePolicyPreview',
                    'ecr:GetDownloadUrlForLayer',
                    'ecr:BatchGetImage',
                    'ecr:DescribeImages',
                    'ecr:GetAuthorizationToken',
                    'ecr:DescribeRepositories',
                    'ecr:ListTagsForResource',
                    'ecr:ListImages',
                    'ecr:BatchCheckLayerAvailability',
                    'ecr:GetRepositoryPolicy',
                    'ecr:GetLifecyclePolicy'
                  ]
                Resource: '*'
