---
AWSTemplateFormatVersion: '2010-09-09'
Description: Snyk integration for AWS Lambda. (qs-1qqfgjgbc)
Outputs:
  SnykLambdaIntegrationRole:
    Description: Amazon Resource Name (ARN) role for Snyk AWS Lambda integration.
    Value: !GetAtt 'SnykLambdaIntegrationRole.Arn'
  Version:
    Description: Snyk Lambda integration version.
    Value: 1.0.2
Metadata:
  QSLint:
    Exclusions: [W9006]
  QuickStartDocumentation:
    EntrypointName: "Snyk integration for AWS Lambda"
    Order: "2"
  LICENSE: Apache License, Version 2.0
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Snyk
        Parameters:
          - SnykExternalId
          - SnykAWSAccountNumber
          - LambdaResourceARN
    ParameterLabels:
      SnykExternalId:
        default: Snyk organization ID(s)
      SnykAWSAccountNumber:
        default: Snyk AWS account ID
      LambdaResourceARN:
        default: ARN for AWS Lambda resources
Parameters:
  SnykExternalId:
    Description: "Locate the organization ID by logging in to https://app.snyk.io and navigating to Settings. To integrate with multiple organizations, separate each ID with a comma."
    Type: CommaDelimitedList
  SnykAWSAccountNumber:
    Description: "Snyk's AWS account ID that assumes a role in your account."
    Type: String
  LambdaResourceARN:
    Description: ARN of the AWS Lambda resources.To list multiple ARNs, separate them with commas.
    Type: CommaDelimitedList
    Default: '*'
Resources:
  SnykLambdaIntegrationRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:${AWS::Partition}:iam::${SnykAWSAccountNumber}:root
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                'sts:ExternalId': !Ref 'SnykExternalId'
      Path: /snyk/
      Policies:
        - PolicyName: SnykReadOnlyForLambda
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  [
                    'lambda:ListFunctions',
                    'lambda:GetAccountSettings'
                  ]
                Resource: '*'
              - Effect: Allow
                Action:
                  [
                    'lambda:GetFunction',
                    'lambda:ListAliases'
                  ]
                Resource: !Ref LambdaResourceARN
