---
AWSTemplateFormatVersion: '2010-09-09'
Description: Snyk integration for AWS Lambda with Serverless CICD Full Stack
Outputs:
  SnykLambdaIntegrationRole:
    Description: Snyk Lambda Integration Role ARN
    Value: !GetAtt 'LambdaIntegrationStack.Outputs.SnykLambdaIntegrationRole'
  Version:
    Description: Snyk Lambda Integration Version
    Value: 1.0.2
Metadata:
  LICENSE: Apache License, Version 2.0
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Snyk
        Parameters:
          - SnykExternalId
      - Label:
          default: Application configuration
        Parameters:
          - AppName
      - Label:
          default: Accounts configuration
        Parameters:
          - DevAwsAccountId
          - DevChildAccountRoleName
          - ProdAwsAccountId
          - ProdChildAccountRoleName
      - Label:
          default: Pipeline configuration
        Parameters:
          - BuildImageName
      - Label:
          default: AWS Quick Start configuration
        Parameters:
          - QSS3BucketName
          - QSS3BucketRegion
          - QSS3KeyPrefix
    ParameterLabels:
      AppName:
        default: Application name
      BuildImageName:
        default: Build image
      DevAwsAccountId:
        default: Development account ID (child)
      DevChildAccountRoleName:
        default: Development account role name
      ProdAwsAccountId:
        default: Production account ID (child)
      ProdChildAccountRoleName:
        default: Production account role name
      QSS3BucketName:
        default: Quick Start S3 bucket name
      QSS3BucketRegion:
        default: Quick Start S3 bucket region
      QSS3KeyPrefix:
        default: Quick Start S3 key prefix
      SnykExternalId:
        default: Snyk Organization ID
Parameters:
  AppName:
    Description: Application name, used for the repository and child stack name
    Type: String
    Default: Sample
  BuildImageName:
    Description: Docker image for application build
    Type: String
    Default: aws/codebuild/nodejs:10.1.0
  DevAwsAccountId:
    Description: AWS account ID for development account
    Type: String
    AllowedPattern: (\d{12}|^$)
    ConstraintDescription: Must be an AWS account ID
  DevChildAccountRoleName:
    Description: Name of role created by ChildAccountRole template in development account
    Type: String
    Default: ChildAccountRole
  ProdAwsAccountId:
    Description: AWS account ID for production account
    Type: String
    AllowedPattern: (\d{12}|^$)
    ConstraintDescription: Must be an AWS account ID
  ProdChildAccountRoleName:
    Description: Name of role created by ChildAccountRole template in production account
    Type: String
    Default: ChildAccountRole
  QSS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription:
      Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen
      (-).
    Default: aws-quickstart
    Description:
      S3 bucket name for the Quick Start assets. This string can include
      numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start
      or end with a hyphen (-).
    Type: String
  QSS3BucketRegion:
    Default: us-west-2
    Description: The AWS Region where the Quick Start S3 bucket (QSS3BucketName) is hosted. When using your own bucket, you must specify this value.
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: ^[0-9a-zA-Z-/.]*$
    ConstraintDescription:
      Quick Start key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), dots(.) and forward slash (/).
    Default: quickstart-snyk-security/
    Description:
      S3 key prefix for the Quick Start assets. Quick Start key prefix
      can include numbers, lowercase letters, uppercase letters, hyphens (-), dots(.) and
      forward slash (/).
    Type: String
  SnykExternalId:
    Description: You may find this by logging into https://app.snyk.io and navigate to Settings.
    Type: String
    AllowedPattern: '[a-z0-9-]{36}'
    MinLength: 1
Conditions:
  UsingDefaultBucket: !Equals
    - !Ref QSS3BucketName
    - 'aws-quickstart'
Resources:
  CICDFulltack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        AppName: !Ref 'AppName'
        BuildImageName: !Ref 'BuildImageName'
        DevAwsAccountId: !Ref 'DevAwsAccountId'
        DevChildAccountRoleName: !Ref 'DevChildAccountRoleName'
        ProdAwsAccountId: !Ref 'ProdAwsAccountId'
        ProdChildAccountRoleName: !Ref 'ProdChildAccountRoleName'
      TemplateURL: !Sub
        - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}submodules/quickstart-trek10-serverless-enterprise-cicd/templates/full-stack.template.yaml'
        - S3Bucket: !If
            - UsingDefaultBucket
            - !Sub 'aws-quickstart-${AWS::Region}'
            - !Ref 'QSS3BucketName'
          S3Region: !If
            - UsingDefaultBucket
            - !Ref 'AWS::Region'
            - !Ref 'QSS3BucketRegion'
  LambdaIntegrationStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        SnykExternalId: !Ref 'SnykExternalId'
      TemplateURL: !Sub
        - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/snyk-lambda.yaml'
        - S3Bucket: !If
            - UsingDefaultBucket
            - !Sub 'aws-quickstart-${AWS::Region}'
            - !Ref 'QSS3BucketName'
          S3Region: !If
            - UsingDefaultBucket
            - !Ref 'AWS::Region'
            - !Ref 'QSS3BucketRegion'
